server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    # 是否从EurekaServer 抓取已有的注册信息，默认是true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
spring:
  application:
    # 订单服务
    name: cloud-order-service