server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:  # 这里就是配置路由的，可以配置多个路由
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配该路由后要转发的目标微服务的访问地址（协议://微服务Ip:微服务端口），还可以是eureka的服务名
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:   #这个是配置断言的，可以胚子和多个断言
            - Path=/payment/get/** # Path表示“路径断言”，及请求路径和Path指定的路径相匹配的才满足断言，才会进行路由

          #解释，当请求路径满足 predicates的断言后，请求就会转发地址为：uri + / + 源Path
          #uri有两种写法，可以直接写 协议://ip:端口，也可以写 lb://微服务在eureka中的服务名，其中lb表示

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - After=2020-03-09T22:40:37.365+08:00[Asia/Shanghai]
          filters:
            - AddRequestParameter=X-Request-Id,1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      # defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/